### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by ImAleeexx** [htdvisser/ssh-gateway#2]
After I make some sftp transfers I get this error and the server crashes completely.
Any solution to this problem???

![image](https://user-images.githubusercontent.com/52298617/123671658-cfc07280-d83e-11eb-8963-a99749469f8c.png)

**Comment by htdvisser** [comment]
The "too many open files" error sounds like the file descriptor limit on your operating system may be a bit too low for the number of connections you're trying to open. You can use `ulimit -n` to find the limit, and a quick Google search will probably tell you how to increase the limit for your OS.

The program however shouldn't crash when reaching the limit; I'll try to fix that.

**Comment by htdvisser** [comment]
Crash fixed in 4f41af65d16c533634d96701951972b02b7ba6c9
